---
- hosts: web
  become: yes

  tasks:

    - name: Install Apache
      apt:
        name: apache2
        state: present
        update_cache: yes

    - name: Start Apache
      service:
        name: apache2
        state: started
        enabled: yes

    - name: Copy index.html
      copy:
        src: ../website/index.html
        dest: /var/www/html/index.html
        owner: root
        group: root
        mode: '0644'

    - name: Copy styles.css
      copy:
        src: ../website/styles.css
        dest: /var/www/html/styles.css
        owner: root
        group: root
        mode: '0644'
